### ISSUE TITLE
distribution request

### ISSUE THREAD

**Issue by archey** [304GEEK/Scrape-DNS#4]
I am a developer for archassault.org we would like to distribute your tool, but I noticed that its missing a license file. Can you please update it to include a license file and give us permission to distribute?

**Comment by 304GEEK** [comment]
See if that works for ya. I would be honored to my script on your distro. good luck!

**Comment by archey** [comment]
Thanks it looks you missed a closing bracket on your usage function
line: function usage() should be function usage(){

**Comment by archey** [comment]
closing this  as script has been added
